// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipeline.proto

package pipeline

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainerArgument struct {
	// Data reference.
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerArgument) Reset()         { *m = ContainerArgument{} }
func (m *ContainerArgument) String() string { return proto.CompactTextString(m) }
func (*ContainerArgument) ProtoMessage()    {}
func (*ContainerArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{0}
}

func (m *ContainerArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerArgument.Unmarshal(m, b)
}
func (m *ContainerArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerArgument.Marshal(b, m, deterministic)
}
func (m *ContainerArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerArgument.Merge(m, src)
}
func (m *ContainerArgument) XXX_Size() int {
	return xxx_messageInfo_ContainerArgument.Size(m)
}
func (m *ContainerArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerArgument.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerArgument proto.InternalMessageInfo

func (m *ContainerArgument) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ContainerArguments struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerArguments) Reset()         { *m = ContainerArguments{} }
func (m *ContainerArguments) String() string { return proto.CompactTextString(m) }
func (*ContainerArguments) ProtoMessage()    {}
func (*ContainerArguments) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{1}
}

func (m *ContainerArguments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerArguments.Unmarshal(m, b)
}
func (m *ContainerArguments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerArguments.Marshal(b, m, deterministic)
}
func (m *ContainerArguments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerArguments.Merge(m, src)
}
func (m *ContainerArguments) XXX_Size() int {
	return xxx_messageInfo_ContainerArguments.Size(m)
}
func (m *ContainerArguments) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerArguments.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerArguments proto.InternalMessageInfo

func (m *ContainerArguments) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataArgument struct {
	// Data reference.
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataArgument) Reset()         { *m = DataArgument{} }
func (m *DataArgument) String() string { return proto.CompactTextString(m) }
func (*DataArgument) ProtoMessage()    {}
func (*DataArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{2}
}

func (m *DataArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataArgument.Unmarshal(m, b)
}
func (m *DataArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataArgument.Marshal(b, m, deterministic)
}
func (m *DataArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataArgument.Merge(m, src)
}
func (m *DataArgument) XXX_Size() int {
	return xxx_messageInfo_DataArgument.Size(m)
}
func (m *DataArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_DataArgument.DiscardUnknown(m)
}

var xxx_messageInfo_DataArgument proto.InternalMessageInfo

func (m *DataArgument) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DataArguments struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataArguments) Reset()         { *m = DataArguments{} }
func (m *DataArguments) String() string { return proto.CompactTextString(m) }
func (*DataArguments) ProtoMessage()    {}
func (*DataArguments) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{3}
}

func (m *DataArguments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataArguments.Unmarshal(m, b)
}
func (m *DataArguments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataArguments.Marshal(b, m, deterministic)
}
func (m *DataArguments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataArguments.Merge(m, src)
}
func (m *DataArguments) XXX_Size() int {
	return xxx_messageInfo_DataArguments.Size(m)
}
func (m *DataArguments) XXX_DiscardUnknown() {
	xxx_messageInfo_DataArguments.DiscardUnknown(m)
}

var xxx_messageInfo_DataArguments proto.InternalMessageInfo

func (m *DataArguments) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrimitiveArgument struct {
	// 0-based index identifying a step of which primitive is used as a value.
	Data                 int32    `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveArgument) Reset()         { *m = PrimitiveArgument{} }
func (m *PrimitiveArgument) String() string { return proto.CompactTextString(m) }
func (*PrimitiveArgument) ProtoMessage()    {}
func (*PrimitiveArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{4}
}

func (m *PrimitiveArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveArgument.Unmarshal(m, b)
}
func (m *PrimitiveArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveArgument.Marshal(b, m, deterministic)
}
func (m *PrimitiveArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveArgument.Merge(m, src)
}
func (m *PrimitiveArgument) XXX_Size() int {
	return xxx_messageInfo_PrimitiveArgument.Size(m)
}
func (m *PrimitiveArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveArgument.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveArgument proto.InternalMessageInfo

func (m *PrimitiveArgument) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type PrimitiveArguments struct {
	// 0-based index identifying a step of which primitive is used as a value.
	Data                 []int32  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveArguments) Reset()         { *m = PrimitiveArguments{} }
func (m *PrimitiveArguments) String() string { return proto.CompactTextString(m) }
func (*PrimitiveArguments) ProtoMessage()    {}
func (*PrimitiveArguments) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{5}
}

func (m *PrimitiveArguments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveArguments.Unmarshal(m, b)
}
func (m *PrimitiveArguments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveArguments.Marshal(b, m, deterministic)
}
func (m *PrimitiveArguments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveArguments.Merge(m, src)
}
func (m *PrimitiveArguments) XXX_Size() int {
	return xxx_messageInfo_PrimitiveArguments.Size(m)
}
func (m *PrimitiveArguments) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveArguments.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveArguments proto.InternalMessageInfo

func (m *PrimitiveArguments) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type ValueArgument struct {
	Data                 *Value   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueArgument) Reset()         { *m = ValueArgument{} }
func (m *ValueArgument) String() string { return proto.CompactTextString(m) }
func (*ValueArgument) ProtoMessage()    {}
func (*ValueArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{6}
}

func (m *ValueArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueArgument.Unmarshal(m, b)
}
func (m *ValueArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueArgument.Marshal(b, m, deterministic)
}
func (m *ValueArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueArgument.Merge(m, src)
}
func (m *ValueArgument) XXX_Size() int {
	return xxx_messageInfo_ValueArgument.Size(m)
}
func (m *ValueArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueArgument.DiscardUnknown(m)
}

var xxx_messageInfo_ValueArgument proto.InternalMessageInfo

func (m *ValueArgument) GetData() *Value {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrimitiveStepArgument struct {
	// Types that are valid to be assigned to Argument:
	//	*PrimitiveStepArgument_Container
	//	*PrimitiveStepArgument_Data
	//	*PrimitiveStepArgument_ContainerList
	Argument             isPrimitiveStepArgument_Argument `protobuf_oneof:"argument"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *PrimitiveStepArgument) Reset()         { *m = PrimitiveStepArgument{} }
func (m *PrimitiveStepArgument) String() string { return proto.CompactTextString(m) }
func (*PrimitiveStepArgument) ProtoMessage()    {}
func (*PrimitiveStepArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{7}
}

func (m *PrimitiveStepArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveStepArgument.Unmarshal(m, b)
}
func (m *PrimitiveStepArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveStepArgument.Marshal(b, m, deterministic)
}
func (m *PrimitiveStepArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveStepArgument.Merge(m, src)
}
func (m *PrimitiveStepArgument) XXX_Size() int {
	return xxx_messageInfo_PrimitiveStepArgument.Size(m)
}
func (m *PrimitiveStepArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveStepArgument.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveStepArgument proto.InternalMessageInfo

type isPrimitiveStepArgument_Argument interface {
	isPrimitiveStepArgument_Argument()
}

type PrimitiveStepArgument_Container struct {
	Container *ContainerArgument `protobuf:"bytes,1,opt,name=container,proto3,oneof"`
}

type PrimitiveStepArgument_Data struct {
	Data *DataArgument `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type PrimitiveStepArgument_ContainerList struct {
	ContainerList *ContainerArguments `protobuf:"bytes,3,opt,name=container_list,json=containerList,proto3,oneof"`
}

func (*PrimitiveStepArgument_Container) isPrimitiveStepArgument_Argument() {}

func (*PrimitiveStepArgument_Data) isPrimitiveStepArgument_Argument() {}

func (*PrimitiveStepArgument_ContainerList) isPrimitiveStepArgument_Argument() {}

func (m *PrimitiveStepArgument) GetArgument() isPrimitiveStepArgument_Argument {
	if m != nil {
		return m.Argument
	}
	return nil
}

func (m *PrimitiveStepArgument) GetContainer() *ContainerArgument {
	if x, ok := m.GetArgument().(*PrimitiveStepArgument_Container); ok {
		return x.Container
	}
	return nil
}

func (m *PrimitiveStepArgument) GetData() *DataArgument {
	if x, ok := m.GetArgument().(*PrimitiveStepArgument_Data); ok {
		return x.Data
	}
	return nil
}

func (m *PrimitiveStepArgument) GetContainerList() *ContainerArguments {
	if x, ok := m.GetArgument().(*PrimitiveStepArgument_ContainerList); ok {
		return x.ContainerList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PrimitiveStepArgument) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PrimitiveStepArgument_Container)(nil),
		(*PrimitiveStepArgument_Data)(nil),
		(*PrimitiveStepArgument_ContainerList)(nil),
	}
}

type PrimitiveStepHyperparameter struct {
	// Types that are valid to be assigned to Argument:
	//	*PrimitiveStepHyperparameter_Container
	//	*PrimitiveStepHyperparameter_Data
	//	*PrimitiveStepHyperparameter_Primitive
	//	*PrimitiveStepHyperparameter_Value
	//	*PrimitiveStepHyperparameter_DataSet
	//	*PrimitiveStepHyperparameter_PrimitivesSet
	Argument             isPrimitiveStepHyperparameter_Argument `protobuf_oneof:"argument"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *PrimitiveStepHyperparameter) Reset()         { *m = PrimitiveStepHyperparameter{} }
func (m *PrimitiveStepHyperparameter) String() string { return proto.CompactTextString(m) }
func (*PrimitiveStepHyperparameter) ProtoMessage()    {}
func (*PrimitiveStepHyperparameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{8}
}

func (m *PrimitiveStepHyperparameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveStepHyperparameter.Unmarshal(m, b)
}
func (m *PrimitiveStepHyperparameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveStepHyperparameter.Marshal(b, m, deterministic)
}
func (m *PrimitiveStepHyperparameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveStepHyperparameter.Merge(m, src)
}
func (m *PrimitiveStepHyperparameter) XXX_Size() int {
	return xxx_messageInfo_PrimitiveStepHyperparameter.Size(m)
}
func (m *PrimitiveStepHyperparameter) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveStepHyperparameter.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveStepHyperparameter proto.InternalMessageInfo

type isPrimitiveStepHyperparameter_Argument interface {
	isPrimitiveStepHyperparameter_Argument()
}

type PrimitiveStepHyperparameter_Container struct {
	Container *ContainerArgument `protobuf:"bytes,1,opt,name=container,proto3,oneof"`
}

type PrimitiveStepHyperparameter_Data struct {
	Data *DataArgument `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type PrimitiveStepHyperparameter_Primitive struct {
	Primitive *PrimitiveArgument `protobuf:"bytes,3,opt,name=primitive,proto3,oneof"`
}

type PrimitiveStepHyperparameter_Value struct {
	Value *ValueArgument `protobuf:"bytes,4,opt,name=value,proto3,oneof"`
}

type PrimitiveStepHyperparameter_DataSet struct {
	DataSet *DataArguments `protobuf:"bytes,5,opt,name=data_set,json=dataSet,proto3,oneof"`
}

type PrimitiveStepHyperparameter_PrimitivesSet struct {
	PrimitivesSet *PrimitiveArguments `protobuf:"bytes,6,opt,name=primitives_set,json=primitivesSet,proto3,oneof"`
}

func (*PrimitiveStepHyperparameter_Container) isPrimitiveStepHyperparameter_Argument() {}

func (*PrimitiveStepHyperparameter_Data) isPrimitiveStepHyperparameter_Argument() {}

func (*PrimitiveStepHyperparameter_Primitive) isPrimitiveStepHyperparameter_Argument() {}

func (*PrimitiveStepHyperparameter_Value) isPrimitiveStepHyperparameter_Argument() {}

func (*PrimitiveStepHyperparameter_DataSet) isPrimitiveStepHyperparameter_Argument() {}

func (*PrimitiveStepHyperparameter_PrimitivesSet) isPrimitiveStepHyperparameter_Argument() {}

func (m *PrimitiveStepHyperparameter) GetArgument() isPrimitiveStepHyperparameter_Argument {
	if m != nil {
		return m.Argument
	}
	return nil
}

func (m *PrimitiveStepHyperparameter) GetContainer() *ContainerArgument {
	if x, ok := m.GetArgument().(*PrimitiveStepHyperparameter_Container); ok {
		return x.Container
	}
	return nil
}

func (m *PrimitiveStepHyperparameter) GetData() *DataArgument {
	if x, ok := m.GetArgument().(*PrimitiveStepHyperparameter_Data); ok {
		return x.Data
	}
	return nil
}

func (m *PrimitiveStepHyperparameter) GetPrimitive() *PrimitiveArgument {
	if x, ok := m.GetArgument().(*PrimitiveStepHyperparameter_Primitive); ok {
		return x.Primitive
	}
	return nil
}

func (m *PrimitiveStepHyperparameter) GetValue() *ValueArgument {
	if x, ok := m.GetArgument().(*PrimitiveStepHyperparameter_Value); ok {
		return x.Value
	}
	return nil
}

func (m *PrimitiveStepHyperparameter) GetDataSet() *DataArguments {
	if x, ok := m.GetArgument().(*PrimitiveStepHyperparameter_DataSet); ok {
		return x.DataSet
	}
	return nil
}

func (m *PrimitiveStepHyperparameter) GetPrimitivesSet() *PrimitiveArguments {
	if x, ok := m.GetArgument().(*PrimitiveStepHyperparameter_PrimitivesSet); ok {
		return x.PrimitivesSet
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PrimitiveStepHyperparameter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PrimitiveStepHyperparameter_Container)(nil),
		(*PrimitiveStepHyperparameter_Data)(nil),
		(*PrimitiveStepHyperparameter_Primitive)(nil),
		(*PrimitiveStepHyperparameter_Value)(nil),
		(*PrimitiveStepHyperparameter_DataSet)(nil),
		(*PrimitiveStepHyperparameter_PrimitivesSet)(nil),
	}
}

type StepInput struct {
	// Data reference.
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StepInput) Reset()         { *m = StepInput{} }
func (m *StepInput) String() string { return proto.CompactTextString(m) }
func (*StepInput) ProtoMessage()    {}
func (*StepInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{9}
}

func (m *StepInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepInput.Unmarshal(m, b)
}
func (m *StepInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepInput.Marshal(b, m, deterministic)
}
func (m *StepInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepInput.Merge(m, src)
}
func (m *StepInput) XXX_Size() int {
	return xxx_messageInfo_StepInput.Size(m)
}
func (m *StepInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StepInput.DiscardUnknown(m)
}

var xxx_messageInfo_StepInput proto.InternalMessageInfo

func (m *StepInput) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type StepOutput struct {
	// Name which becomes part of the data reference.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StepOutput) Reset()         { *m = StepOutput{} }
func (m *StepOutput) String() string { return proto.CompactTextString(m) }
func (*StepOutput) ProtoMessage()    {}
func (*StepOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{10}
}

func (m *StepOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepOutput.Unmarshal(m, b)
}
func (m *StepOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepOutput.Marshal(b, m, deterministic)
}
func (m *StepOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepOutput.Merge(m, src)
}
func (m *StepOutput) XXX_Size() int {
	return xxx_messageInfo_StepOutput.Size(m)
}
func (m *StepOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StepOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StepOutput proto.InternalMessageInfo

func (m *StepOutput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PipelineSource struct {
	// String representing name of the author, team.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// An URI to contact the source.
	Contact string `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	// A list of pipelines used to derive the pipeline.
	Pipelines            []*PipelineDescription `protobuf:"bytes,3,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PipelineSource) Reset()         { *m = PipelineSource{} }
func (m *PipelineSource) String() string { return proto.CompactTextString(m) }
func (*PipelineSource) ProtoMessage()    {}
func (*PipelineSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{11}
}

func (m *PipelineSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineSource.Unmarshal(m, b)
}
func (m *PipelineSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineSource.Marshal(b, m, deterministic)
}
func (m *PipelineSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineSource.Merge(m, src)
}
func (m *PipelineSource) XXX_Size() int {
	return xxx_messageInfo_PipelineSource.Size(m)
}
func (m *PipelineSource) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineSource.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineSource proto.InternalMessageInfo

func (m *PipelineSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PipelineSource) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *PipelineSource) GetPipelines() []*PipelineDescription {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

// User associated with the creation of the template/pipeline, or selection of a primitive.
type PipelineDescriptionUser struct {
	// Globally unique ID for this user. It can be opaque, but it should identify the same user
	// across sessions. Consider using UUID variant 5 with namespace set to the name of your system
	// and name to an ID in your system's database. It does not have to map to any real ID, just
	// that it is possible to connect multiple pipelines/templates by the same user together,
	// if necessary.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A natural language description of what the user did to be on the list, e.g., "Picked
	// a pipeline from a list of pipelines.".
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// A natural language description by the user of what the user did,
	// e.g., "I picked a pipeline because it looks short in comparison with others.".
	Rationale            string   `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineDescriptionUser) Reset()         { *m = PipelineDescriptionUser{} }
func (m *PipelineDescriptionUser) String() string { return proto.CompactTextString(m) }
func (*PipelineDescriptionUser) ProtoMessage()    {}
func (*PipelineDescriptionUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{12}
}

func (m *PipelineDescriptionUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineDescriptionUser.Unmarshal(m, b)
}
func (m *PipelineDescriptionUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineDescriptionUser.Marshal(b, m, deterministic)
}
func (m *PipelineDescriptionUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineDescriptionUser.Merge(m, src)
}
func (m *PipelineDescriptionUser) XXX_Size() int {
	return xxx_messageInfo_PipelineDescriptionUser.Size(m)
}
func (m *PipelineDescriptionUser) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineDescriptionUser.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineDescriptionUser proto.InternalMessageInfo

func (m *PipelineDescriptionUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PipelineDescriptionUser) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PipelineDescriptionUser) GetRationale() string {
	if m != nil {
		return m.Rationale
	}
	return ""
}

// Possible input to the pipeline or template.
type PipelineDescriptionInput struct {
	// Human friendly name of the input.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineDescriptionInput) Reset()         { *m = PipelineDescriptionInput{} }
func (m *PipelineDescriptionInput) String() string { return proto.CompactTextString(m) }
func (*PipelineDescriptionInput) ProtoMessage()    {}
func (*PipelineDescriptionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{13}
}

func (m *PipelineDescriptionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineDescriptionInput.Unmarshal(m, b)
}
func (m *PipelineDescriptionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineDescriptionInput.Marshal(b, m, deterministic)
}
func (m *PipelineDescriptionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineDescriptionInput.Merge(m, src)
}
func (m *PipelineDescriptionInput) XXX_Size() int {
	return xxx_messageInfo_PipelineDescriptionInput.Size(m)
}
func (m *PipelineDescriptionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineDescriptionInput.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineDescriptionInput proto.InternalMessageInfo

func (m *PipelineDescriptionInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Available output of the pipeline or template.
type PipelineDescriptionOutput struct {
	// Human friendly name of the output.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Data reference, probably of an output of a step.
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineDescriptionOutput) Reset()         { *m = PipelineDescriptionOutput{} }
func (m *PipelineDescriptionOutput) String() string { return proto.CompactTextString(m) }
func (*PipelineDescriptionOutput) ProtoMessage()    {}
func (*PipelineDescriptionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{14}
}

func (m *PipelineDescriptionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineDescriptionOutput.Unmarshal(m, b)
}
func (m *PipelineDescriptionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineDescriptionOutput.Marshal(b, m, deterministic)
}
func (m *PipelineDescriptionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineDescriptionOutput.Merge(m, src)
}
func (m *PipelineDescriptionOutput) XXX_Size() int {
	return xxx_messageInfo_PipelineDescriptionOutput.Size(m)
}
func (m *PipelineDescriptionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineDescriptionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineDescriptionOutput proto.InternalMessageInfo

func (m *PipelineDescriptionOutput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PipelineDescriptionOutput) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PrimitivePipelineDescriptionStep struct {
	Primitive *Primitive `protobuf:"bytes,1,opt,name=primitive,proto3" json:"primitive,omitempty"`
	// Arguments to the primitive. Constructor arguments should not be listed here, because they
	// can be automatically created from other information. All these arguments are listed as kind
	// "PIPELINE" in primitive's metadata.
	Arguments map[string]*PrimitiveStepArgument `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// List of produce methods providing data. One can reference using data reference these outputs
	// then in arguments (inputs) in other steps or pipeline outputs.
	Outputs []*StepOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Some hyper-parameters are not really tunable and should be fixed as part of template/pipeline.
	// This can be done here. Hyper-parameters listed here cannot be tuned or overridden. Author of a
	// template/pipeline decides which hyper-parameter are which, probably based on their semantic type.
	// TA3 can specify a list of hyper-parameters to fix, and TA2 can add to the list additional
	// hyper-parameters in found pipelines.
	Hyperparams map[string]*PrimitiveStepHyperparameter `protobuf:"bytes,4,rep,name=hyperparams,proto3" json:"hyperparams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// List of users associated with selection of this primitive/arguments/hyper-parameters. Optional.
	Users                []*PipelineDescriptionUser `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PrimitivePipelineDescriptionStep) Reset()         { *m = PrimitivePipelineDescriptionStep{} }
func (m *PrimitivePipelineDescriptionStep) String() string { return proto.CompactTextString(m) }
func (*PrimitivePipelineDescriptionStep) ProtoMessage()    {}
func (*PrimitivePipelineDescriptionStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{15}
}

func (m *PrimitivePipelineDescriptionStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitivePipelineDescriptionStep.Unmarshal(m, b)
}
func (m *PrimitivePipelineDescriptionStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitivePipelineDescriptionStep.Marshal(b, m, deterministic)
}
func (m *PrimitivePipelineDescriptionStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitivePipelineDescriptionStep.Merge(m, src)
}
func (m *PrimitivePipelineDescriptionStep) XXX_Size() int {
	return xxx_messageInfo_PrimitivePipelineDescriptionStep.Size(m)
}
func (m *PrimitivePipelineDescriptionStep) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitivePipelineDescriptionStep.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitivePipelineDescriptionStep proto.InternalMessageInfo

func (m *PrimitivePipelineDescriptionStep) GetPrimitive() *Primitive {
	if m != nil {
		return m.Primitive
	}
	return nil
}

func (m *PrimitivePipelineDescriptionStep) GetArguments() map[string]*PrimitiveStepArgument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *PrimitivePipelineDescriptionStep) GetOutputs() []*StepOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *PrimitivePipelineDescriptionStep) GetHyperparams() map[string]*PrimitiveStepHyperparameter {
	if m != nil {
		return m.Hyperparams
	}
	return nil
}

func (m *PrimitivePipelineDescriptionStep) GetUsers() []*PipelineDescriptionUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type SubpipelinePipelineDescriptionStep struct {
	// Only "id" field is required in this case to reference another pipeline in the template.
	Pipeline *PipelineDescription `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// List of data references, probably of an output of a step or pipeline input,
	// mapped to sub-pipeline's inputs in order.
	Inputs []*StepInput `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// List of IDs to be used in data references, mapping sub-pipeline's outputs in order.
	Outputs              []*StepOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SubpipelinePipelineDescriptionStep) Reset()         { *m = SubpipelinePipelineDescriptionStep{} }
func (m *SubpipelinePipelineDescriptionStep) String() string { return proto.CompactTextString(m) }
func (*SubpipelinePipelineDescriptionStep) ProtoMessage()    {}
func (*SubpipelinePipelineDescriptionStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{16}
}

func (m *SubpipelinePipelineDescriptionStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubpipelinePipelineDescriptionStep.Unmarshal(m, b)
}
func (m *SubpipelinePipelineDescriptionStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubpipelinePipelineDescriptionStep.Marshal(b, m, deterministic)
}
func (m *SubpipelinePipelineDescriptionStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubpipelinePipelineDescriptionStep.Merge(m, src)
}
func (m *SubpipelinePipelineDescriptionStep) XXX_Size() int {
	return xxx_messageInfo_SubpipelinePipelineDescriptionStep.Size(m)
}
func (m *SubpipelinePipelineDescriptionStep) XXX_DiscardUnknown() {
	xxx_messageInfo_SubpipelinePipelineDescriptionStep.DiscardUnknown(m)
}

var xxx_messageInfo_SubpipelinePipelineDescriptionStep proto.InternalMessageInfo

func (m *SubpipelinePipelineDescriptionStep) GetPipeline() *PipelineDescription {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *SubpipelinePipelineDescriptionStep) GetInputs() []*StepInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *SubpipelinePipelineDescriptionStep) GetOutputs() []*StepOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// Used to represent a pipeline template which can be used to generate full pipelines.
// A placeholder is replaced with a pipeline step to form a pipeline. See README.md
// for restrictions on the number of them, their position, allowed inputs and outputs,
// etc.
type PlaceholderPipelineDescriptionStep struct {
	// List of inputs which can be used as inputs to resulting sub-pipeline. Resulting
	// sub-pipeline does not have to use all the inputs, but it cannot use any other inputs.
	Inputs []*StepInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// A list of outputs of the resulting sub-pipeline.
	Outputs              []*StepOutput `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlaceholderPipelineDescriptionStep) Reset()         { *m = PlaceholderPipelineDescriptionStep{} }
func (m *PlaceholderPipelineDescriptionStep) String() string { return proto.CompactTextString(m) }
func (*PlaceholderPipelineDescriptionStep) ProtoMessage()    {}
func (*PlaceholderPipelineDescriptionStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{17}
}

func (m *PlaceholderPipelineDescriptionStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceholderPipelineDescriptionStep.Unmarshal(m, b)
}
func (m *PlaceholderPipelineDescriptionStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceholderPipelineDescriptionStep.Marshal(b, m, deterministic)
}
func (m *PlaceholderPipelineDescriptionStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceholderPipelineDescriptionStep.Merge(m, src)
}
func (m *PlaceholderPipelineDescriptionStep) XXX_Size() int {
	return xxx_messageInfo_PlaceholderPipelineDescriptionStep.Size(m)
}
func (m *PlaceholderPipelineDescriptionStep) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceholderPipelineDescriptionStep.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceholderPipelineDescriptionStep proto.InternalMessageInfo

func (m *PlaceholderPipelineDescriptionStep) GetInputs() []*StepInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *PlaceholderPipelineDescriptionStep) GetOutputs() []*StepOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type PipelineDescriptionStep struct {
	// Types that are valid to be assigned to Step:
	//	*PipelineDescriptionStep_Primitive
	//	*PipelineDescriptionStep_Pipeline
	//	*PipelineDescriptionStep_Placeholder
	Step                 isPipelineDescriptionStep_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *PipelineDescriptionStep) Reset()         { *m = PipelineDescriptionStep{} }
func (m *PipelineDescriptionStep) String() string { return proto.CompactTextString(m) }
func (*PipelineDescriptionStep) ProtoMessage()    {}
func (*PipelineDescriptionStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{18}
}

func (m *PipelineDescriptionStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineDescriptionStep.Unmarshal(m, b)
}
func (m *PipelineDescriptionStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineDescriptionStep.Marshal(b, m, deterministic)
}
func (m *PipelineDescriptionStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineDescriptionStep.Merge(m, src)
}
func (m *PipelineDescriptionStep) XXX_Size() int {
	return xxx_messageInfo_PipelineDescriptionStep.Size(m)
}
func (m *PipelineDescriptionStep) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineDescriptionStep.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineDescriptionStep proto.InternalMessageInfo

type isPipelineDescriptionStep_Step interface {
	isPipelineDescriptionStep_Step()
}

type PipelineDescriptionStep_Primitive struct {
	Primitive *PrimitivePipelineDescriptionStep `protobuf:"bytes,1,opt,name=primitive,proto3,oneof"`
}

type PipelineDescriptionStep_Pipeline struct {
	Pipeline *SubpipelinePipelineDescriptionStep `protobuf:"bytes,2,opt,name=pipeline,proto3,oneof"`
}

type PipelineDescriptionStep_Placeholder struct {
	Placeholder *PlaceholderPipelineDescriptionStep `protobuf:"bytes,3,opt,name=placeholder,proto3,oneof"`
}

func (*PipelineDescriptionStep_Primitive) isPipelineDescriptionStep_Step() {}

func (*PipelineDescriptionStep_Pipeline) isPipelineDescriptionStep_Step() {}

func (*PipelineDescriptionStep_Placeholder) isPipelineDescriptionStep_Step() {}

func (m *PipelineDescriptionStep) GetStep() isPipelineDescriptionStep_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *PipelineDescriptionStep) GetPrimitive() *PrimitivePipelineDescriptionStep {
	if x, ok := m.GetStep().(*PipelineDescriptionStep_Primitive); ok {
		return x.Primitive
	}
	return nil
}

func (m *PipelineDescriptionStep) GetPipeline() *SubpipelinePipelineDescriptionStep {
	if x, ok := m.GetStep().(*PipelineDescriptionStep_Pipeline); ok {
		return x.Pipeline
	}
	return nil
}

func (m *PipelineDescriptionStep) GetPlaceholder() *PlaceholderPipelineDescriptionStep {
	if x, ok := m.GetStep().(*PipelineDescriptionStep_Placeholder); ok {
		return x.Placeholder
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PipelineDescriptionStep) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PipelineDescriptionStep_Primitive)(nil),
		(*PipelineDescriptionStep_Pipeline)(nil),
		(*PipelineDescriptionStep_Placeholder)(nil),
	}
}

// Pipeline description matches the D3M pipeline description.
// It serves two purposes: describing found pipelines by TA2 to TA3, and communicating pipeline
// templates by TA3 to TA2. Because of this some fields are reasonable only in one of those uses.
// They are marked with "TA2" or "TA3" in the comment, for fields which are primarily to be set
// only by TA2 or only by TA3, respectively.
type PipelineDescription struct {
	// TA2: UUID of the pipeline. Templates do not have IDs. But TA3 might provide it for a fully
	// specified pipeline. It does not necessary have to match "solution_id" from
	// "ListSolutionsResponse" and other related messages. Those IDs are about whole solutions
	// (pipeline, potentially fitted, with set hyper-parameters). This here ID is about this
	// particular ID description.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// "schema" field is not needed because it is fixed by the TA2-TA3 protocol version.
	// System which generated a pipeline or a template. Optional.
	Source *PipelineSource `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// TA2: Timestamp when created. Templates do not have this timestamp. TA3 might provide it for
	// a fully specified pipeline.
	Created *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	// Human friendly name of the pipeline. For templates it can be a hint to
	// TA2 how to name found pipelines. Optional.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Human friendly description of the pipeline. Optional.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// List of users associated with the creation of the template and consequently of the pipeline.
	// TA2 can store this information into metalearning database. TA2 is not really expected to use
	// this information during pipeline search. TA2 should not have to understand TA3 users, mapping
	// between users and pipeline search IDs is something TA3 should handle. Optional.
	Users []*PipelineDescriptionUser `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	// In most cases inputs are datasets. But if TA3 wants to jut run a primitive, it can send a
	// template with only that primitive in the template, and then pass anything to its inputs during
	// execution. Here, we are describing possible inputs to the pipeline or template. Order matters.
	Inputs []*PipelineDescriptionInput `protobuf:"bytes,8,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Available outputs of the pipeline or template.
	Outputs []*PipelineDescriptionOutput `protobuf:"bytes,9,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Steps defining the pipeline.
	Steps                []*PipelineDescriptionStep `protobuf:"bytes,10,rep,name=steps,proto3" json:"steps,omitempty"`
	Digest               string                     `protobuf:"bytes,11,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PipelineDescription) Reset()         { *m = PipelineDescription{} }
func (m *PipelineDescription) String() string { return proto.CompactTextString(m) }
func (*PipelineDescription) ProtoMessage()    {}
func (*PipelineDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{19}
}

func (m *PipelineDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineDescription.Unmarshal(m, b)
}
func (m *PipelineDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineDescription.Marshal(b, m, deterministic)
}
func (m *PipelineDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineDescription.Merge(m, src)
}
func (m *PipelineDescription) XXX_Size() int {
	return xxx_messageInfo_PipelineDescription.Size(m)
}
func (m *PipelineDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineDescription.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineDescription proto.InternalMessageInfo

func (m *PipelineDescription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PipelineDescription) GetSource() *PipelineSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *PipelineDescription) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *PipelineDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PipelineDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PipelineDescription) GetUsers() []*PipelineDescriptionUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PipelineDescription) GetInputs() []*PipelineDescriptionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *PipelineDescription) GetOutputs() []*PipelineDescriptionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *PipelineDescription) GetSteps() []*PipelineDescriptionStep {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *PipelineDescription) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainerArgument)(nil), "ContainerArgument")
	proto.RegisterType((*ContainerArguments)(nil), "ContainerArguments")
	proto.RegisterType((*DataArgument)(nil), "DataArgument")
	proto.RegisterType((*DataArguments)(nil), "DataArguments")
	proto.RegisterType((*PrimitiveArgument)(nil), "PrimitiveArgument")
	proto.RegisterType((*PrimitiveArguments)(nil), "PrimitiveArguments")
	proto.RegisterType((*ValueArgument)(nil), "ValueArgument")
	proto.RegisterType((*PrimitiveStepArgument)(nil), "PrimitiveStepArgument")
	proto.RegisterType((*PrimitiveStepHyperparameter)(nil), "PrimitiveStepHyperparameter")
	proto.RegisterType((*StepInput)(nil), "StepInput")
	proto.RegisterType((*StepOutput)(nil), "StepOutput")
	proto.RegisterType((*PipelineSource)(nil), "PipelineSource")
	proto.RegisterType((*PipelineDescriptionUser)(nil), "PipelineDescriptionUser")
	proto.RegisterType((*PipelineDescriptionInput)(nil), "PipelineDescriptionInput")
	proto.RegisterType((*PipelineDescriptionOutput)(nil), "PipelineDescriptionOutput")
	proto.RegisterType((*PrimitivePipelineDescriptionStep)(nil), "PrimitivePipelineDescriptionStep")
	proto.RegisterMapType((map[string]*PrimitiveStepArgument)(nil), "PrimitivePipelineDescriptionStep.ArgumentsEntry")
	proto.RegisterMapType((map[string]*PrimitiveStepHyperparameter)(nil), "PrimitivePipelineDescriptionStep.HyperparamsEntry")
	proto.RegisterType((*SubpipelinePipelineDescriptionStep)(nil), "SubpipelinePipelineDescriptionStep")
	proto.RegisterType((*PlaceholderPipelineDescriptionStep)(nil), "PlaceholderPipelineDescriptionStep")
	proto.RegisterType((*PipelineDescriptionStep)(nil), "PipelineDescriptionStep")
	proto.RegisterType((*PipelineDescription)(nil), "PipelineDescription")
}

func init() { proto.RegisterFile("pipeline.proto", fileDescriptor_7ac67a7adf3df9c7) }

var fileDescriptor_7ac67a7adf3df9c7 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xce, 0x4f, 0x93, 0xd4, 0xc7, 0x34, 0xbb, 0x3b, 0x0b, 0x8b, 0x37, 0x54, 0xda, 0xe2, 0x08,
	0x1a, 0x69, 0xd1, 0xec, 0x12, 0xf6, 0x02, 0x21, 0x6e, 0xda, 0x5d, 0x84, 0x91, 0x10, 0x54, 0x93,
	0xc2, 0x05, 0x42, 0xaa, 0xa6, 0xc9, 0x90, 0xb5, 0x48, 0x6c, 0x6b, 0x66, 0xbc, 0x52, 0x9f, 0x85,
	0x2b, 0x5e, 0x83, 0x37, 0xe0, 0x6d, 0x78, 0x01, 0x24, 0x34, 0xe3, 0x99, 0xb1, 0x5d, 0x3b, 0x4d,
	0x6f, 0xb8, 0x8b, 0x33, 0xdf, 0xf9, 0xce, 0x99, 0xef, 0x7c, 0xe7, 0xd8, 0x30, 0xce, 0xe2, 0x8c,
	0x6d, 0xe2, 0x84, 0xe1, 0x8c, 0xa7, 0x32, 0x9d, 0x3c, 0x5b, 0xa7, 0xe9, 0x7a, 0xc3, 0x5e, 0xe8,
	0xa7, 0xeb, 0xfc, 0xb7, 0x17, 0x32, 0xde, 0x32, 0x21, 0xe9, 0x36, 0x33, 0x80, 0x07, 0x19, 0x8f,
	0xb7, 0xb1, 0x8c, 0xdf, 0xd9, 0x08, 0xff, 0x1d, 0xdd, 0xe4, 0xe6, 0x21, 0x3c, 0x85, 0x47, 0xaf,
	0xd3, 0x44, 0xd2, 0x38, 0x61, 0xfc, 0x8c, 0xaf, 0xf3, 0x2d, 0x4b, 0x24, 0x42, 0x70, 0xb0, 0xa2,
	0x92, 0x06, 0xdd, 0x93, 0xee, 0xcc, 0x23, 0xfa, 0x77, 0x38, 0x03, 0xd4, 0x00, 0x8a, 0x0a, 0xb2,
	0xef, 0x90, 0x21, 0xbc, 0xf7, 0x86, 0x4a, 0x7a, 0x27, 0xdb, 0x14, 0x8e, 0xaa, 0x98, 0x76, 0xa2,
	0x53, 0x78, 0x74, 0x61, 0x6b, 0x6f, 0x65, 0x1b, 0x94, 0xb5, 0x35, 0x80, 0x75, 0x4a, 0x8b, 0x7c,
	0x0e, 0x47, 0x3f, 0xab, 0xdb, 0x3b, 0xba, 0x49, 0x85, 0xce, 0x9f, 0x0f, 0xb1, 0x3e, 0x35, 0xe0,
	0xbf, 0xba, 0xf0, 0x81, 0xe3, 0x5d, 0x48, 0x96, 0xb9, 0xa8, 0x39, 0x78, 0x4b, 0x2b, 0x86, 0x09,
	0x45, 0xb8, 0x21, 0x4f, 0xd4, 0x21, 0x25, 0x0c, 0x4d, 0x4d, 0xa6, 0x9e, 0x86, 0x1f, 0xe1, 0xea,
	0xfd, 0xa3, 0x4e, 0x91, 0x12, 0x7d, 0x0d, 0x63, 0x17, 0x71, 0xb5, 0x89, 0x85, 0x0c, 0xfa, 0x1a,
	0xfe, 0xb8, 0xc9, 0x2e, 0xa2, 0x0e, 0x39, 0x72, 0xe0, 0xef, 0x63, 0x21, 0xcf, 0x01, 0x0e, 0xa9,
	0x39, 0x0d, 0xff, 0xee, 0xc1, 0x47, 0xb5, 0xe2, 0xa3, 0x9b, 0x8c, 0xf1, 0x8c, 0x72, 0xba, 0x65,
	0x92, 0xf1, 0xff, 0xef, 0x0a, 0x73, 0xf0, 0x9c, 0xe3, 0x4c, 0xf5, 0x08, 0x37, 0xda, 0xa3, 0x88,
	0x1d, 0x0c, 0x7d, 0x0a, 0x03, 0x6d, 0xca, 0xe0, 0x40, 0xe3, 0xc7, 0xb8, 0xd6, 0xa4, 0xa8, 0x43,
	0x8a, 0x63, 0xf4, 0x1c, 0x0e, 0x55, 0x8e, 0x2b, 0xc1, 0x64, 0x30, 0x30, 0xd0, 0x9a, 0x8f, 0xa2,
	0x0e, 0x19, 0x29, 0xc4, 0x82, 0x49, 0xa5, 0xa5, 0xcb, 0x20, 0x74, 0xc8, 0xd0, 0x68, 0xd9, 0x34,
	0x8b, 0xd2, 0xb2, 0x04, 0x2f, 0x58, 0x5d, 0xcb, 0x67, 0xe0, 0x29, 0x05, 0xbf, 0x4b, 0xb2, 0xbc,
	0xdd, 0xce, 0xc7, 0x00, 0x0a, 0xf0, 0x63, 0x2e, 0x15, 0x62, 0x0c, 0xbd, 0x78, 0x65, 0xce, 0x7b,
	0xf1, 0x2a, 0xe4, 0x30, 0xbe, 0x30, 0x43, 0xbb, 0x48, 0x73, 0xbe, 0x64, 0x8a, 0x23, 0xa1, 0x5b,
	0x66, 0x39, 0xd4, 0x6f, 0x14, 0xc0, 0x48, 0x2b, 0xbd, 0x94, 0x5a, 0x5f, 0x8f, 0xd8, 0x47, 0xad,
	0xa8, 0x89, 0x17, 0x41, 0xff, 0xa4, 0x3f, 0xf3, 0xe7, 0xef, 0x63, 0xcb, 0xf8, 0x86, 0x89, 0x25,
	0x8f, 0x33, 0x19, 0xa7, 0x09, 0x29, 0x61, 0xe1, 0x15, 0x7c, 0xd8, 0x82, 0xf8, 0x49, 0x30, 0x7e,
	0xbb, 0x3c, 0xf4, 0x04, 0x86, 0x9c, 0x51, 0x91, 0x26, 0x26, 0xaf, 0x79, 0x42, 0xc7, 0xe0, 0x71,
	0xaa, 0xa2, 0xe8, 0xa6, 0x68, 0xa4, 0x47, 0xca, 0x3f, 0x42, 0x0c, 0x41, 0x4b, 0x02, 0x27, 0xd1,
	0xed, 0xeb, 0x85, 0xaf, 0xe1, 0x69, 0x0b, 0xde, 0x28, 0xd6, 0xa6, 0x07, 0xaa, 0x98, 0xcd, 0xea,
	0xfc, 0x6f, 0x1f, 0x4e, 0x5c, 0xf3, 0x5a, 0xe8, 0x54, 0x13, 0xd0, 0xac, 0x6a, 0xc0, 0xc2, 0xd9,
	0x50, 0xb6, 0xbc, 0x6a, 0xbb, 0x1f, 0xc0, 0xb3, 0x3d, 0x16, 0x41, 0x4f, 0x0b, 0xfb, 0x12, 0xef,
	0xe3, 0xc7, 0xce, 0x34, 0xdf, 0x24, 0x92, 0xdf, 0x90, 0x92, 0x02, 0x7d, 0x02, 0xa3, 0x54, 0x5f,
	0xc8, 0xb6, 0xc9, 0xc7, 0xa5, 0x2d, 0x88, 0x3d, 0x43, 0x97, 0xe0, 0xbf, 0x75, 0xc3, 0x28, 0x82,
	0x03, 0x0d, 0x9d, 0xef, 0x4f, 0x5c, 0x4e, 0xb0, 0x49, 0x5d, 0xa5, 0x41, 0x18, 0x06, 0xb9, 0x60,
	0x5c, 0x04, 0x03, 0xcd, 0x17, 0xe0, 0x1d, 0xfd, 0x27, 0x05, 0x6c, 0x72, 0x09, 0xe3, 0xfa, 0x4d,
	0xd0, 0x43, 0xe8, 0xff, 0xce, 0x6e, 0x4c, 0x13, 0xd4, 0x4f, 0xf4, 0x99, 0x9d, 0xcb, 0x62, 0xe2,
	0x9f, 0xe0, 0xd6, 0x75, 0x68, 0xa6, 0xf3, 0xab, 0xde, 0x97, 0xdd, 0xc9, 0xaf, 0xf0, 0xf0, 0x76,
	0x99, 0x2d, 0xbc, 0xf3, 0x3a, 0xef, 0x31, 0xbe, 0x63, 0x53, 0x55, 0xd8, 0xc3, 0x3f, 0xbb, 0x10,
	0x2e, 0xf2, 0x6b, 0x6b, 0xf3, 0x5d, 0x0e, 0x78, 0x09, 0x87, 0x16, 0x62, 0x0c, 0xd0, 0x3e, 0x2f,
	0x0e, 0x85, 0x42, 0x18, 0xc6, 0x89, 0x6e, 0x5c, 0x61, 0x03, 0xc0, 0x6e, 0xe0, 0x89, 0x39, 0xb9,
	0x67, 0x77, 0xc3, 0x14, 0xc2, 0x8b, 0x0d, 0x5d, 0xb2, 0xb7, 0xe9, 0x66, 0xc5, 0xf8, 0xae, 0x12,
	0xcb, 0x84, 0xdd, 0xfb, 0x24, 0xec, 0xdd, 0x91, 0xf0, 0x9f, 0x6e, 0xeb, 0xac, 0xeb, 0x34, 0x67,
	0xcd, 0x59, 0xf8, 0x78, 0xaf, 0xd1, 0xea, 0xbb, 0xf9, 0xac, 0x22, 0x66, 0xd1, 0xae, 0x29, 0xde,
	0xdf, 0x83, 0xa8, 0x53, 0x51, 0xf7, 0x5b, 0xf0, 0xb3, 0x52, 0x12, 0xf3, 0x52, 0x98, 0xe2, 0xfd,
	0x32, 0x45, 0x1d, 0x52, 0x8d, 0x3c, 0x1f, 0xc2, 0x81, 0x90, 0x2c, 0x0b, 0xff, 0xe8, 0xc3, 0xe3,
	0x96, 0x90, 0xc6, 0x6a, 0x3b, 0x85, 0xa1, 0xd0, 0x1b, 0xd7, 0x54, 0xfe, 0x00, 0xd7, 0x17, 0x31,
	0x31, 0xc7, 0xe8, 0x15, 0x8c, 0x96, 0x9c, 0x51, 0xc9, 0x56, 0xa6, 0xba, 0x09, 0x2e, 0xbe, 0xab,
	0xb0, 0xfd, 0xae, 0xc2, 0x97, 0xf6, 0xbb, 0x8a, 0x58, 0xa8, 0x5b, 0x5b, 0x83, 0xca, 0xda, 0x3a,
	0x01, 0x7f, 0x55, 0x56, 0xa4, 0x5f, 0x39, 0x1e, 0xa9, 0xfe, 0x55, 0x0e, 0xea, 0xe8, 0x5e, 0x83,
	0x8a, 0x3e, 0x77, 0x56, 0x39, 0xd4, 0x01, 0x4f, 0xf1, 0xae, 0xc5, 0xeb, 0x9c, 0xf3, 0xaa, 0x74,
	0x8e, 0xa7, 0x63, 0x26, 0x78, 0xe7, 0xf2, 0x2d, 0xf7, 0x12, 0x86, 0x81, 0x52, 0x57, 0x04, 0xb0,
	0xbb, 0x30, 0xd5, 0x15, 0x52, 0xc0, 0xd4, 0x8b, 0x63, 0x15, 0xaf, 0x99, 0x90, 0x81, 0x5f, 0xbc,
	0x38, 0x8a, 0xa7, 0x73, 0xf8, 0xc5, 0xb5, 0xfe, 0x7a, 0xa8, 0xf5, 0xfb, 0xe2, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x68, 0x08, 0x7c, 0xcb, 0xb7, 0x0a, 0x00, 0x00,
}
